server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/delivery_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  elasticsearch:
    uris: http://elasticsearch:9200
    connection-timeout: 5s
    socket-timeout: 3s
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: health, info

springdoc:
  swagger-ui:
    path: /swagger-ui.html

catalog:
  service-url: http://catalog-service:8081/api/products
