server:
  port: 8080
spring:
  application:
    name: gateway-service

management:
  endpoints:
    web:
      exposure:
        include: health, gateway, info, routes

jwt:
  secret: ${JWT_SECRET} # en producción se lee de variable de entorno
