server:
  port: 8080
spring:
  application:
    name: gateway-service

management:
  endpoints:
    web:
      exposure:
        include: health, gateway, info, routes

jwt:
  secret: ${JWT_SECRET} # en producción se lee de variable de entorno

springdoc:
  swagger-ui:
    urls:
      - name: gateway
        url: /v3/api-docs
      - name: auth-service
        url: /api/docs/auth
      - name: catalog-service
        url: /api/docs/catalog
      - name: order-service
        url: /api/docs/order
      - name: delivery-service
        url: /api/docs/delivery
      - name: file-service
        url: /api/docs/file
