server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    org.springframework.web.reactive.function.client.ExchangeFilterFunction: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, gateway, info, routes

jwt:
  secret: mysecretkeymysecretkeymysecretkey1234

springdoc:
  swagger-ui:
    urls:
      - name: gateway
        url: /v3/api-docs
      - name: auth-service
        url: /api/docs/auth
      - name: catalog-service
        url: /api/docs/catalog
      - name: order-service
        url: /api/docs/order
      - name: delivery-service
        url: /api/docs/delivery
      - name: file-service
        url: /api/docs/file
