server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/delivery_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # No queremos que modifique la estructura en prod
    show-sql: false       # No queremos SQL logs en prod
    properties:
      hibernate:
        format_sql: false

management:
  endpoints:
    web:
      exposure:
        include: health, info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
