server:
  port: 8086

spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

aws:
  s3:
    access-key: YOUR_ACCESS_KEY
    secret-key: YOUR_SECRET_KEY
    region: us-east-1
    bucket: delivery-files
    endpoint: http://minio:8086