server:
  port: 8083

spring:
  application:
    name: auth-service

  r2dbc:
    url: r2dbc:postgresql://db:5432/delivery_db
    username: postgres
    password: postgres

  sql:
    init:
      platform: postgres

logging:
  level:
    root: INFO

springdoc:
  swagger-ui:
    csrf:
      enabled: false
    oauth2-redirect-url: ""
    persist-authorization: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  default-produces-media-type: application/json

jwt:
  secret: mysecretkeymysecretkeymysecretkey1234
  expiration: 86400000 # 1 día
