version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: delivery_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  catalog-service:
    build:
      context: ./backend/catalog-service
    container_name: catalog-service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod

  order-service:
    build:
      context: ./backend/order-service
    container_name: order-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - catalog-service
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod

volumes:
  postgres_data:
  minio_data:

